In [25]:
import pandas as pd
import numpy as np
df = pd.read_excel('data/processed/cities.xlsx')
df

,name,id_city,name_microregion,id_microregion,name_macroregion,id_macroregion,name_state,id_state,Sigla UF,region_name
0,Alta Floresta D'Oeste,1100015,Cacoal,11006,Leste Rondoniense,1102,Rondônia,11,RO,Norte
1,Ariquemes,1100023,Ariquemes,11003,Leste Rondoniense,1102,Rondônia,11,RO,Norte
2,Cabixi,1100031,Colorado do Oeste,11008,Leste Rondoniense,1102,Rondônia,11,RO,Norte
3,Cacoal,1100049,Cacoal,11006,Leste Rondoniense,1102,Rondônia,11,RO,Norte
4,Cerejeiras,1100056,Colorado do Oeste,11008,Leste Rondoniense,1102,Rondônia,11,RO,Norte
...,...,...,...,...,...,...,...,...,...,...
5565,Vianópolis,5222005,Pires do Rio,52016,Sul Goiano,5205,Goiás,52,GO,Centro-Oeste
5566,Vicentinópolis,5222054,Meia Ponte,52015,Sul Goiano,5205,Goiás,52,GO,Centro-Oeste
5567,Vila Boa,5222203,Entorno de Brasília,52012,Leste Goiano,5204,Goiás,52,GO,Centro-Oeste
5568,Vila Propício,5222302,Entorno de Brasília,52012,Leste Goiano,5204,Goiás,52,GO,Centro-Oeste
5569,Brasília,5300108,Brasília,53001,Distrito Federal,5301,Distrito Federal,53,DF,Centro-Oeste

In [3]:
# checking for duplicates in ids?
col = 'id_city'
df[col].loc[df[col].duplicated()]

Series([], Name: id_city, dtype: int64)

In [4]:
# tons of duplicate city names
df.loc[df['name'].duplicated()]

,name,id_city,name_microregion,id_microregion,name_macroregion,id_macroregion,name_state,id_state,Sigla UF,region_name
335,Bom Jesus do Tocantins,1703305,Porto Nacional,17006,Oriental do Tocantins,1702,Tocantins,17,TO,Norte
403,Pau D'Arco,1716307,Araguaína,17002,Ocidental do Tocantins,1701,Tocantins,17,TO,Norte
464,Araguanã,2100873,Pindaré,21008,Oeste Maranhense,2102,Maranhão,21,MA,Nordeste
601,Presidente Médici,2109239,Pindaré,21008,Oeste Maranhense,2102,Maranhão,21,MA,Nordeste
745,Esperantina,2203701,Baixo Parnaíba Piauiense,22001,Norte Piauiense,2201,Piauí,22,PI,Nordeste
...,...,...,...,...,...,...,...,...,...,...
5506,Piranhas,5217203,Aragarças,52003,Noroeste Goiano,5201,Goiás,52,GO,Centro-Oeste
5527,Santa Isabel,5219357,Ceres,52006,Centro Goiano,5203,Goiás,52,GO,Centro-Oeste
5536,São Domingos,5219803,Vão do Paranã,52011,Leste Goiano,5204,Goiás,52,GO,Centro-Oeste
5545,São Simão,5220405,Quirinópolis,52018,Sul Goiano,5205,Goiás,52,GO,Centro-Oeste
5555,Trindade,5221403,Goiânia,52010,Centro Goiano,5203,Goiás,52,GO,Centro-Oeste

In [5]:
# let's check if there are duplicate names within the same state
# there are not. 

ref_col = 'region_name'
unique_states = df[ref_col].unique()

for state in unique_states:
    data = df.loc[df[ref_col] == state]
    dupes = data['name'].loc[data['name'].duplicated()]
    if dupes.empty is False:
        display(dupes)

335    Bom Jesus do Tocantins
403                Pau D'Arco
Name: name, dtype: object

1093                  Bom Jesus
1205    São Gonçalo do Amarante
1225                 Sítio Novo
1242                Água Branca
1263                    Baraúna
                 ...
2179               São Domingos
2201                   Serrinha
2212                    Taperoá
2218                 Terra Nova
2237                  Vera Cruz
Name: name, Length: 68, dtype: object

3109           Boa Esperança
3192               Cantagalo
3217                Mesquita
3523                 Itapeva
3729    Presidente Bernardes
3759               Rio Claro
3814           São Francisco
3862                 Tapiraí
3886               Turmalina
Name: name, dtype: object

4372         Catanduvas
4432              Irati
4493           Palmeira
4540       Santa Helena
4589              Turvo
4640           Barracão
4654          Bom Jesus
4717           Colorado
4732    Cruzeiro do Sul
4926           Planalto
5008       São Martinho
5026            Sarandi
5044           Tapejara
Name: name, dtype: object

5476    Mundo Novo
Name: name, dtype: object

In [8]:
data = pd.read_excel('data/processed/soy.xlsx')
data = data.loc[data['Tipo região'] == 'Município']
data

,Local,Área plantada (Hectares),Área colhida (Hectares),Quantidade produzida (Toneladas),Rendimento médio da produção (Quilogramas por Hectare),Valor da produção (Mil Reais),UF,Tipo região
3,Cruzeiro do Sul,0,0,0,0,0,Acre,Município
4,Mâncio Lima,0,0,0,0,0,Acre,Município
5,Marechal Thaumaturgo,0,0,0,0,0,Acre,Município
6,Porto Walter,0,0,0,0,0,Acre,Município
7,Rodrigues Alves,0,0,0,0,0,Acre,Município
...,...,...,...,...,...,...,...,...
6287,Itarumã,4500,4500,14850,3300,39605,Goias,Município
6288,Lagoa Santa,0,0,0,0,0,Goias,Município
6289,Paranaiguara,2800,2800,9300,3321,24803,Goias,Município
6290,Quirinópolis,33000,33000,108900,3300,290436,Goias,Município
6291,São Simão,0,0,0,0,0,Goias,Município

In [28]:
def get_id(series):
    # gets id based on name
    id = df.loc[df['name'] == series['Local'], 'id_city']
    # id = df.at[df['name'] == series['Local'], 'id_city']
    # display(id)
    if id.empty:
        return np.nan
    else:
        return id.values[0]

# bla = get_id(data.loc[4])
# bla

data['id'] = data.apply(get_id, axis=1)
data

,Local,Área plantada (Hectares),Área colhida (Hectares),Quantidade produzida (Toneladas),Rendimento médio da produção (Quilogramas por Hectare),Valor da produção (Mil Reais),UF,Tipo região,id
3,Cruzeiro do Sul,0,0,0,0,0,Acre,Município,1200203.0
4,Mâncio Lima,0,0,0,0,0,Acre,Município,1200336.0
5,Marechal Thaumaturgo,0,0,0,0,0,Acre,Município,1200351.0
6,Porto Walter,0,0,0,0,0,Acre,Município,1200393.0
7,Rodrigues Alves,0,0,0,0,0,Acre,Município,1200427.0
...,...,...,...,...,...,...,...,...,...
6287,Itarumã,4500,4500,14850,3300,39605,Goias,Município,5211305.0
6288,Lagoa Santa,0,0,0,0,0,Goias,Município,3137601.0
6289,Paranaiguara,2800,2800,9300,3321,24803,Goias,Município,5216304.0
6290,Quirinópolis,33000,33000,108900,3300,290436,Goias,Município,5218508.0
6291,São Simão,0,0,0,0,0,Goias,Município,3550902.0